# Generated by Django 5.2.1 on 2025-06-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField()),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('gateway_type', models.CharField(choices=[('EDGEX', 'EdgeX'), ('SIMPLE', 'Simple'), ('CUSTOM', 'Custom')], max_length=10)),
            ],
        ),
    ]
