# Generated by Django 5.2.1 on 2025-06-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_alter_gateway_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('OFFLINE', 'Offline'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=10),
            preserve_default=False,
        ),
    ]
