# Generated by Django 5.2.1 on 2025-06-04 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_gateway_last_seen_gateway_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gateway',
            old_name='state',
            new_name='status',
        ),
    ]
