# Generated by Django 5.2.1 on 2025-06-19 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_rename_state_gateway_status'),
        ('profiles', '0002_alter_resourceproperties_valuetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField()),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.deviceprofile')),
            ],
        ),
        migrations.AddField(
            model_name='gateway',
            name='profiles',
            field=models.ManyToManyField(through='gateway.GatewayProfiles', to='profiles.deviceprofile'),
        ),
    ]
