# Generated by Django 5.2.1 on 2025-07-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_gatewayprofiles_gateway_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
