# Generated by Django 5.2.1 on 2025-07-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_gateway_password_gateway_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='password',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
