# Generated by Django 5.2.1 on 2025-07-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0007_alter_gateway_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='token',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
