# Generated by Django 5.2.1 on 2025-07-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0008_gateway_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='api_port',
            field=models.IntegerField(default=443),
        ),
    ]
