# Generated by Django 5.2.1 on 2025-06-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField()),
                ('admin_state', models.CharField(choices=[('UNLOCKED', 'Unlocked'), ('LOCKED', 'Locked')], default='UNLOCKED', max_length=10)),
                ('operating_state', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('UNKNOWN', 'Unknown')], default='UP', max_length=10)),
                ('labels', models.ManyToManyField(to='devices.labels')),
            ],
        ),
    ]
