# Generated by Django 5.2.1 on 2025-06-02 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('profiles', '0002_alter_resourceproperties_valuetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.deviceprofile'),
            preserve_default=False,
        ),
    ]
