# Generated by Django 5.2.1 on 2025-06-04 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_profile'),
        ('gateway', '0004_rename_state_gateway_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='gateway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.gateway'),
        ),
    ]
