# Generated by Django 5.2.1 on 2025-06-18 22:20

import uuid
from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    Device = apps.get_model('devices', 'Device')
    for device in Device.objects.all():
        device.uid = uuid.uuid4()
        device.save()

class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(generate_unique_uuids),
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AlterField(
            model_name="device",
            name="uid",
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False),
        )
    ]
