# Generated by Django 5.2.1 on 2025-06-18 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_device_id_device_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='uid',
            new_name='id',
        ),
    ]
