# Generated by Django 5.2.1 on 2025-07-16 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_rename_uid_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='labels',
        ),
    ]
