# Generated by Django 5.2.1 on 2025-07-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_remove_device_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='labels',
            field=models.ManyToManyField(to='devices.labels'),
        ),
    ]
