# Generated by Django 5.2.1 on 2025-06-30 02:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.RemoveField(
            model_name='data',
            name='valueType',
        ),
        migrations.AddField(
            model_name='data',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
