# Generated by Django 5.2.1 on 2025-06-01 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField()),
                ('model', models.CharField()),
                ('description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueType', models.CharField(choices=[('UINT8', 'Uint8'), ('UINT16', 'Uint16'), ('UINT32', 'Uint32'), ('UINT64', 'Uint64'), ('INT8', 'Int8'), ('INT16', 'Int16'), ('INT32', 'Int32'), ('INT64', 'Int64'), ('FLOAT32', 'Float32'), ('FLOAT64', 'Float64'), ('BOOL', 'Bool'), ('STRING', 'String'), ('BINARY', 'Binary'), ('OBJECT', 'Object'), ('UINT8_ARRAY', 'Uint8Array'), ('UINT16_ARRAY', 'Uint16Array'), ('UINT32_ARRAY', 'Uint32Array'), ('UINT64_ARRAY', 'Uint64Array'), ('INT8_ARRAY', 'Int8Array'), ('INT16_ARRAY', 'Int16Array'), ('INT32_ARRAY', 'Int32Array'), ('INT64_ARRAY', 'Int64Array'), ('FLOAT32_ARRAY', 'Float32Array'), ('FLOAT64_ARRAY', 'Float64Array'), ('BOOL_ARRAY', 'BoolArray')], max_length=20)),
                ('readWrite', models.CharField(choices=[('R', 'Read'), ('W', 'Write'), ('RW', 'Read and Write')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('readWrite', models.CharField(choices=[('R', 'Read'), ('W', 'Write'), ('RW', 'Read and Write')], max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='profiles.deviceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='profiles.deviceprofile')),
                ('properties', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.resourceproperties')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultValue', models.CharField()),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='profiles.devicecommand')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.deviceresource')),
            ],
        ),
        migrations.AddField(
            model_name='deviceprofile',
            name='labels',
            field=models.ManyToManyField(to='profiles.labels'),
        ),
    ]
