# Generated by Django 5.2.1 on 2025-06-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceproperties',
            name='valueType',
            field=models.CharField(choices=[('Uint8', 'Uint8'), ('Uint16', 'Uint16'), ('Uint32', 'Uint32'), ('Uint64', 'Uint64'), ('Int8', 'Int8'), ('Int16', 'Int16'), ('Int32', 'Int32'), ('Int64', 'Int64'), ('Float32', 'Float32'), ('Float64', 'Float64'), ('Bool', 'Bool'), ('String', 'String'), ('Binary', 'Binary'), ('Object', 'Object'), ('Uint8Array', 'Uint8Array'), ('Uint16Array', 'Uint16Array'), ('Uint32Array', 'Uint32Array'), ('Uint64Array', 'Uint64Array'), ('Int8Array', 'Int8Array'), ('Int16Array', 'Int16Array'), ('Int32Array', 'Int32Array'), ('Int64Array', 'Int64Array'), ('Float32Array', 'Float32Array'), ('Float64Array', 'Float64Array'), ('BoolArray', 'BoolArray')], max_length=20),
        ),
    ]
